export type Lang = "it" | "en" | "ja";
export const LANGS: Lang[] = ["it", "en", "ja"];

export const CHROME: Record<Lang, Record<string, string>> = {
  it: {
    test: "MODALITÀ TEST",
    educator: "Educator",
    chooseLang: "Scegli la lingua dell'esame",
    question: "Domanda",
    of: "di",
    back: "Indietro",
    next: "Avanti",
    finish: "Termina",
    start: "Inizia",
    empty: "Questo test non contiene ancora domande.",
    thanksTitle: "Grazie, hai terminato.",
    thanksBody: "Le tue risposte sono state registrate. Puoi chiudere questa pagina.",
    saveErrTitle: "Salvataggio non riuscito",
    saveErrBody: "Le tue risposte NON sono state salvate. Controlla la connessione e riprova.",
    retry: "Riprova",
    yourAnswer: "La tua risposta",
    pendingTitle: "Domande in sospeso",
    pendingBody: "Hai {n} domande senza risposta. Vuoi rivederle prima di terminare?",
    review: "Rivedi le domande saltate",
    finishAnyway: "Termina comunque",
    regName: "Nome e cognome",
    regGender: "Sesso alla nascita",
    regNationality: "Nazionalità",
    regEmail: "Email",
    regPhone: "Telefono",
    regAddress: "Indirizzo di spedizione del materiale",
    male: "Maschile",
    female: "Femminile",
    iDone: "Ho finito",
    emailInvalid: "Inserisci un'email valida",
    emptyListTitle: "Domande lasciate vuote",
    notesTitle: "Le tue note",
    notesHint: "Campo per le tue note: rimane costante durante tutte le risposte dell'esame e non viene salvato.",
    skipped: "Saltate",
    reviewing: "Revisione domande saltate",
    allReviewed: "Hai completato tutte le domande saltate.",
    exitReview: "Esci dalla revisione",
    dragHint: "Trascina o usa le frecce per ordinare",
    previewTitle: "Anteprima · esito calcolato",
    previewScore: "Punteggio (domande oggettive)",
    previewPassed: "Promosso",
    previewRetrial: "Recupero",
    previewFailed: "Non superato",
    previewManual: "domande aperte da valutare a mano",
    previewNotGradable: "Nessuna domanda a correzione automatica in questo test.",
    previewNote: "Questa è un'anteprima: nessun esito è stato salvato.",
    waitTitle: "Sei in sala d'attesa",
    waitBody: "Attendi che l'educator ti ammetta all'esame. Resta su questa pagina.",
    gateMoment: "Un attimo…",
    gateRosterErr: "Impossibile caricare l'elenco della classe.",
    gateCheckInErr: "Check-in non riuscito.",
    submittedTitle: "Esame già consegnato",
    submittedBody: "Hai già completato e inviato questo esame.",
    pickTitle: "Chi sei?",
    pickHint: "Seleziona il tuo nome. L'educator ti ammetterà dopo averti riconosciuto su Zoom.",
    pickSearch: "Cerca il tuo nome…",
    pickNoMatch: "Nessun nome trovato.",
    waitBodyZoom: "attendi che l'educator ti ammetta all'esame. Resta su questa pagina e con la videocamera accesa su Zoom.",
  },
  en: {
    test: "TEST MODE",
    educator: "Educator",
    chooseLang: "Choose the exam language",
    question: "Question",
    of: "of",
    back: "Back",
    next: "Next",
    finish: "Finish",
    start: "Start",
    empty: "This test has no questions yet.",
    thanksTitle: "Thank you, you're done.",
    thanksBody: "Your answers have been recorded. You can close this page.",
    saveErrTitle: "Saving failed",
    saveErrBody: "Your answers were NOT saved. Check your connection and try again.",
    retry: "Try again",
    yourAnswer: "Your answer",
    pendingTitle: "Pending questions",
    pendingBody: "You have {n} unanswered questions. Review them before finishing?",
    review: "Review skipped questions",
    finishAnyway: "Finish anyway",
    regName: "Full name",
    regGender: "Sex at birth",
    regNationality: "Nationality",
    regEmail: "Email",
    regPhone: "Phone",
    regAddress: "Shipping address for materials",
    male: "Male",
    female: "Female",
    iDone: "I'm done",
    emailInvalid: "Enter a valid email",
    emptyListTitle: "Questions left empty",
    notesTitle: "Your notes",
    notesHint: "A space for your notes: it stays the same across all exam questions and is not saved.",
    skipped: "Skipped",
    reviewing: "Reviewing skipped questions",
    allReviewed: "You've completed all skipped questions.",
    exitReview: "Exit review",
    dragHint: "Drag or use the arrows to order",
    previewTitle: "Preview · computed result",
    previewScore: "Score (objective questions)",
    previewPassed: "Passed",
    previewRetrial: "Retrial",
    previewFailed: "Not passed",
    previewManual: "open questions to grade manually",
    previewNotGradable: "No auto-gradable questions in this test.",
    previewNote: "This is a preview: no result was saved.",
    waitTitle: "You're in the waiting room",
    waitBody: "Wait for the educator to admit you to the exam. Stay on this page.",
    gateMoment: "One moment…",
    gateRosterErr: "Unable to load the class roster.",
    gateCheckInErr: "Check-in failed.",
    submittedTitle: "Exam already submitted",
    submittedBody: "You have already completed and submitted this exam.",
    pickTitle: "Who are you?",
    pickHint: "Select your name. The educator will admit you after recognizing you on Zoom.",
    pickSearch: "Search for your name…",
    pickNoMatch: "No name found.",
    waitBodyZoom: "wait for the educator to admit you to the exam. Stay on this page with your camera on in Zoom.",
  },
  ja: {
    test: "テストモード",
    educator: "講師",
    chooseLang: "試験の言語を選択",
    question: "問題",
    of: "/",
    back: "戻る",
    next: "次へ",
    finish: "終了",
    start: "開始",
    empty: "このテストにはまだ問題がありません。",
    thanksTitle: "お疲れさまでした。終了です。",
    thanksBody: "回答が記録されました。このページを閉じてかまいません。",
    saveErrTitle: "保存に失敗しました",
    saveErrBody: "回答は保存されていません。接続を確認して、もう一度お試しください。",
    retry: "再試行",
    yourAnswer: "あなたの回答",
    pendingTitle: "未回答の問題",
    pendingBody: "未回答の問題が{n}件あります。終了前に確認しますか？",
    review: "スキップした問題を確認",
    finishAnyway: "このまま終了",
    regName: "氏名",
    regGender: "出生時の性別",
    regNationality: "国籍",
    regEmail: "メール",
    regPhone: "電話番号",
    regAddress: "教材の配送先住所",
    male: "男性",
    female: "女性",
    iDone: "完了",
    emailInvalid: "有効なメールを入力してください",
    emptyListTitle: "未回答の問題",
    notesTitle: "メモ",
    notesHint: "メモ用の欄です。試験中ずっと保持され、保存されません。",
    skipped: "スキップ",
    reviewing: "スキップした問題の確認",
    allReviewed: "スキップした問題をすべて完了しました。",
    exitReview: "確認を終了",
    dragHint: "ドラッグまたは矢印で並べ替え",
    previewTitle: "プレビュー・計算結果",
    previewScore: "得点（客観式問題）",
    previewPassed: "合格",
    previewRetrial: "再試験",
    previewFailed: "不合格",
    previewManual: "手動採点の記述式問題",
    previewNotGradable: "このテストには自動採点できる問題がありません。",
    previewNote: "これはプレビューです。結果は保存されていません。",
    waitTitle: "待機室にいます",
    waitBody: "教員が試験への参加を許可するまでお待ちください。このページのままにしてください。",
    gateMoment: "少々お待ちください…",
    gateRosterErr: "クラスの名簿を読み込めませんでした。",
    gateCheckInErr: "チェックインに失敗しました。",
    submittedTitle: "試験は提出済みです",
    submittedBody: "この試験はすでに完了して提出されています。",
    pickTitle: "あなたはどなたですか？",
    pickHint: "お名前を選択してください。教員がZoomで確認してから参加を許可します。",
    pickSearch: "お名前を検索…",
    pickNoMatch: "該当する名前が見つかりません。",
    waitBodyZoom: "教員が試験への参加を許可するまでお待ちください。このページのまま、Zoomでカメラをオンにしてお待ちください。",
  },
};

export const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
