export type Lang = "it" | "en" | "ja";
export const LANGS: Lang[] = ["it", "en", "ja"];

export const CHROME: Record<Lang, Record<string, string>> = {
  it: {
    test: "MODALITÀ TEST",
    educator: "Educator",
    chooseLang: "Scegli la lingua dell'esame",
    question: "Domanda",
    of: "di",
    back: "Indietro",
    next: "Avanti",
    finish: "Termina",
    start: "Inizia",
    empty: "Questo test non contiene ancora domande.",
    thanksTitle: "Grazie, hai terminato.",
    thanksBody: "Le tue risposte sono state registrate. Puoi chiudere questa pagina.",
    saveErrTitle: "Salvataggio non riuscito",
    saveErrBody: "Le tue risposte NON sono state salvate. Controlla la connessione e riprova.",
    retry: "Riprova",
    yourAnswer: "La tua risposta",
    pendingTitle: "Domande in sospeso",
    pendingBody: "Hai {n} domande senza risposta. Vuoi rivederle prima di terminare?",
    review: "Rivedi le domande saltate",
    finishAnyway: "Termina comunque",
    regName: "Nome e cognome",
    regGender: "Sesso alla nascita",
    regNationality: "Nazionalità",
    regEmail: "Email",
    regPhone: "Telefono",
    regAddress: "Indirizzo di spedizione del materiale",
    regDob: "Data di nascita (es. 1 gennaio 1990)",
    regOccupation: "Occupazione / professione",
    regResidency: "Paese di residenza",
    male: "Maschile",
    female: "Femminile",
    iDone: "Ho finito",
    emailInvalid: "Inserisci un'email valida",
    emptyListTitle: "Domande lasciate vuote",
    notesTitle: "Le tue note",
    notesHint: "Campo per le tue note: rimane costante durante tutte le risposte dell'esame e non viene salvato.",
    skipped: "Saltate",
    reviewing: "Revisione domande saltate",
    allReviewed: "Hai completato tutte le domande saltate.",
    exitReview: "Esci dalla revisione",
    dragHint: "Trascina o usa le frecce per ordinare",
    previewTitle: "Anteprima · esito calcolato",
    previewScore: "Punteggio (domande oggettive)",
    previewPassed: "Promosso",
    previewRetrial: "Recupero",
    previewFailed: "Non superato",
    previewManual: "domande aperte da valutare a mano",
    previewNotGradable: "Nessuna domanda a correzione automatica in questo test.",
    previewNote: "Questa è un'anteprima: nessun esito è stato salvato.",
    timeWarnTitle: "Ancora 10 minuti",
    timeWarnBody: "Hai ancora 10 minuti per completare l'esame.",
    certDoneTitle: "Grazie per aver sostenuto l'esame",
    certDoneBody: "L'esame è certificato. Nei prossimi giorni riceverai l'esito.",
    // Day tests (giorno 1..N) are NOT the exam → no "certified / result" claim.
    dayDoneTitle: "Grazie",
    gateMoment: "Un attimo…",
    submittedTitle: "Esame già consegnato",
    submittedBody: "Hai già completato e inviato questo esame.",
    dayResultTitle: "Il tuo risultato",
    dayResultNote: "Risultato del test giornaliero — uno strumento SSA per orientare il tuo studio.",
    dayResultReturn: "Puoi rivedere questo esito riaprendo il tuo link, finché resta attivo.",
    reviewList: "Le tue risposte",
    reviewCorrectAnswer: "Risposta corretta",
    reviewPendingBadge: "in valutazione",
    explainBtn: "Approfondisci",
    explainLoading: "Preparo l'approfondimento…",
    explainFail: "Approfondimento non disponibile ora.",
    explainSource: "Dalla Knowledge Base SSA",
  },
  en: {
    test: "TEST MODE",
    educator: "Educator",
    chooseLang: "Choose the exam language",
    question: "Question",
    of: "of",
    back: "Back",
    next: "Next",
    finish: "Finish",
    start: "Start",
    empty: "This test has no questions yet.",
    thanksTitle: "Thank you, you're done.",
    thanksBody: "Your answers have been recorded. You can close this page.",
    saveErrTitle: "Saving failed",
    saveErrBody: "Your answers were NOT saved. Check your connection and try again.",
    retry: "Try again",
    yourAnswer: "Your answer",
    pendingTitle: "Pending questions",
    pendingBody: "You have {n} unanswered questions. Review them before finishing?",
    review: "Review skipped questions",
    finishAnyway: "Finish anyway",
    regName: "Full name",
    regGender: "Sex at birth",
    regNationality: "Nationality",
    regEmail: "Email",
    regPhone: "Phone",
    regAddress: "Shipping address for materials",
    regDob: "Date of birth (e.g. 1 January 1990)",
    regOccupation: "Occupation / profession",
    regResidency: "Country of residency",
    male: "Male",
    female: "Female",
    iDone: "I'm done",
    emailInvalid: "Enter a valid email",
    emptyListTitle: "Questions left empty",
    notesTitle: "Your notes",
    notesHint: "A space for your notes: it stays the same across all exam questions and is not saved.",
    skipped: "Skipped",
    reviewing: "Reviewing skipped questions",
    allReviewed: "You've completed all skipped questions.",
    exitReview: "Exit review",
    dragHint: "Drag or use the arrows to order",
    previewTitle: "Preview · computed result",
    previewScore: "Score (objective questions)",
    previewPassed: "Passed",
    previewRetrial: "Retrial",
    previewFailed: "Not passed",
    previewManual: "open questions to grade manually",
    previewNotGradable: "No auto-gradable questions in this test.",
    previewNote: "This is a preview: no result was saved.",
    timeWarnTitle: "10 minutes left",
    timeWarnBody: "You have 10 minutes left to finish the exam.",
    certDoneTitle: "Thank you for taking the exam",
    certDoneBody: "This exam is certified. You will receive your result in the next few days.",
    dayDoneTitle: "Thank you",
    gateMoment: "One moment…",
    submittedTitle: "Exam already submitted",
    submittedBody: "You have already completed and submitted this exam.",
    dayResultTitle: "Your result",
    dayResultNote: "Day-test result — an SSA study aid to guide your preparation.",
    dayResultReturn: "You can review this result by reopening your link while it stays active.",
    reviewList: "Your answers",
    reviewCorrectAnswer: "Correct answer",
    reviewPendingBadge: "under review",
    explainBtn: "Learn more",
    explainLoading: "Preparing the deep-dive…",
    explainFail: "Deep-dive not available right now.",
    explainSource: "From the SSA Knowledge Base",
  },
  ja: {
    test: "テストモード",
    educator: "講師",
    chooseLang: "試験の言語を選択",
    question: "問題",
    of: "/",
    back: "戻る",
    next: "次へ",
    finish: "終了",
    start: "開始",
    empty: "このテストにはまだ問題がありません。",
    thanksTitle: "お疲れさまでした。終了です。",
    thanksBody: "回答が記録されました。このページを閉じてかまいません。",
    saveErrTitle: "保存に失敗しました",
    saveErrBody: "回答は保存されていません。接続を確認して、もう一度お試しください。",
    retry: "再試行",
    yourAnswer: "あなたの回答",
    pendingTitle: "未回答の問題",
    pendingBody: "未回答の問題が{n}件あります。終了前に確認しますか？",
    review: "スキップした問題を確認",
    finishAnyway: "このまま終了",
    regName: "氏名",
    regGender: "出生時の性別",
    regNationality: "国籍",
    regEmail: "メール",
    regPhone: "電話番号",
    regAddress: "教材の配送先住所",
    regDob: "生年月日（例：1990年1月1日）",
    regOccupation: "職業",
    regResidency: "居住国",
    male: "男性",
    female: "女性",
    iDone: "完了",
    emailInvalid: "有効なメールを入力してください",
    emptyListTitle: "未回答の問題",
    notesTitle: "メモ",
    notesHint: "メモ用の欄です。試験中ずっと保持され、保存されません。",
    skipped: "スキップ",
    reviewing: "スキップした問題の確認",
    allReviewed: "スキップした問題をすべて完了しました。",
    exitReview: "確認を終了",
    dragHint: "ドラッグまたは矢印で並べ替え",
    previewTitle: "プレビュー・計算結果",
    previewScore: "得点（客観式問題）",
    previewPassed: "合格",
    previewRetrial: "再試験",
    previewFailed: "不合格",
    previewManual: "手動採点の記述式問題",
    previewNotGradable: "このテストには自動採点できる問題がありません。",
    previewNote: "これはプレビューです。結果は保存されていません。",
    timeWarnTitle: "残り10分",
    timeWarnBody: "試験終了まで残り10分です。",
    certDoneTitle: "受験ありがとうございました",
    certDoneBody: "この試験は認定されています。数日以内に結果をお知らせします。",
    dayDoneTitle: "ありがとうございました",
    gateMoment: "少々お待ちください…",
    submittedTitle: "試験は提出済みです",
    submittedBody: "この試験はすでに完了して提出されています。",
    dayResultTitle: "あなたの結果",
    dayResultNote: "デイテストの結果 — 学習の指針となるSSAのツールです。",
    dayResultReturn: "リンクが有効な間は、再度開いてこの結果を確認できます。",
    reviewList: "あなたの回答",
    reviewCorrectAnswer: "正解",
    reviewPendingBadge: "評価中",
    explainBtn: "詳しく学ぶ",
    explainLoading: "解説を準備しています…",
    explainFail: "現在、解説をご利用いただけません。",
    explainSource: "SSAナレッジベースより",
  },
};

export const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
